spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache
    username: root
    password: idyllo
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.106.84.237
    port: 6379
  cache:
    redis:
      use-key-prefix: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.llman.cache.mapper: debug

debug: true

