spring:
  jpa:
    # \u5728\u63A7\u5236\u53F0\u6253\u5370\u6267\u884C\u7684SQL
    show-sql: true
    hibernate:
      # \u66F4\u65B0\u6216\u521B\u5EFA\u6570\u636E\u5E93\u8868
      ddl-auto: update
  datasource:
    username: root
    password: idyllo
    url: jdbc:mysql://47.106.84.237:3306/jpa
    driver-class-name: com.mysql.cj.jdbc.Driver

